title: Qingxiang Chen
description: Research tools for history, science, and curious minds
url: https://chen-qingxiang.github.io
language: en
timezone: Australia/Sydney
permalink: /blog/:title/
theme: jekyll-theme-cayman
author:
  name: Qingxiang Chen
github_username: Chen-Qingxiang
