window.ELEMENTS = [
  {n:1,s:'H',zh:'氢',en:'Hydrogen',ipa:'/ˈhaɪdrədʒən/',p:1,g:1,c:'nonmetal'},
  {n:2,s:'He',zh:'氦',en:'Helium',ipa:'/ˈhiːliəm/',p:1,g:18,c:'noble'},
  {n:3,s:'Li',zh:'锂',en:'Lithium',ipa:'/ˈlɪθiəm/',p:2,g:1,c:'alkali'},
  {n:4,s:'Be',zh:'铍',en:'Beryllium',ipa:'/bəˈrɪliəm/',p:2,g:2,c:'alkaline'},
  {n:5,s:'B',zh:'硼',en:'Boron',ipa:'/ˈbɔːrɒn/',p:2,g:13,c:'metalloid'},
  {n:6,s:'C',zh:'碳',en:'Carbon',ipa:'/ˈkɑːrbən/',p:2,g:14,c:'nonmetal'},
  {n:7,s:'N',zh:'氮',en:'Nitrogen',ipa:'/ˈnaɪtrədʒən/',p:2,g:15,c:'nonmetal'},
  {n:8,s:'O',zh:'氧',en:'Oxygen',ipa:'/ˈɒksɪdʒən/',p:2,g:16,c:'nonmetal'},
  {n:9,s:'F',zh:'氟',en:'Fluorine',ipa:'/ˈflʊəriːn/',p:2,g:17,c:'halogen'},
  {n:10,s:'Ne',zh:'氖',en:'Neon',ipa:'/ˈniːɒn/',p:2,g:18,c:'noble'},
  {n:11,s:'Na',zh:'钠',en:'Sodium',ipa:'/ˈsoʊdiəm/',p:3,g:1,c:'alkali'},
  {n:12,s:'Mg',zh:'镁',en:'Magnesium',ipa:'/mæɡˈniːziəm/',p:3,g:2,c:'alkaline'},
  {n:13,s:'Al',zh:'铝',en:'Aluminium',ipa:'/ˌæljʊˈmɪniəm/',p:3,g:13,c:'post'},
  {n:14,s:'Si',zh:'硅',en:'Silicon',ipa:'/ˈsɪlɪkən/',p:3,g:14,c:'metalloid'},
  {n:15,s:'P',zh:'磷',en:'Phosphorus',ipa:'/ˈfɒsfərəs/',p:3,g:15,c:'nonmetal'},
  {n:16,s:'S',zh:'硫',en:'Sulfur',ipa:'/ˈsʌlfər/',p:3,g:16,c:'nonmetal'},
  {n:17,s:'Cl',zh:'氯',en:'Chlorine',ipa:'/ˈklɔːriːn/',p:3,g:17,c:'halogen'},
  {n:18,s:'Ar',zh:'氩',en:'Argon',ipa:'/ˈɑːrɡɒn/',p:3,g:18,c:'noble'},
  {n:19,s:'K',zh:'钾',en:'Potassium',ipa:'/pəˈtæsiəm/',p:4,g:1,c:'alkali'},
  {n:20,s:'Ca',zh:'钙',en:'Calcium',ipa:'/ˈkælsiəm/',p:4,g:2,c:'alkaline'},
  {n:21,s:'Sc',zh:'钪',en:'Scandium',ipa:'/ˈskændiəm/',p:4,g:3,c:'transition'},
  {n:22,s:'Ti',zh:'钛',en:'Titanium',ipa:'/taɪˈteɪniəm/',p:4,g:4,c:'transition'},
  {n:23,s:'V',zh:'钒',en:'Vanadium',ipa:'/vəˈneɪdiəm/',p:4,g:5,c:'transition'},
  {n:24,s:'Cr',zh:'铬',en:'Chromium',ipa:'/ˈkroʊmiəm/',p:4,g:6,c:'transition'},
  {n:25,s:'Mn',zh:'锰',en:'Manganese',ipa:'/ˈmæŋɡəniːz/',p:4,g:7,c:'transition'},
  {n:26,s:'Fe',zh:'铁',en:'Iron',ipa:'/ˈaɪərn/',p:4,g:8,c:'transition'},
  {n:27,s:'Co',zh:'钴',en:'Cobalt',ipa:'/ˈkoʊbɔːlt/',p:4,g:9,c:'transition'},
  {n:28,s:'Ni',zh:'镍',en:'Nickel',ipa:'/ˈnɪkəl/',p:4,g:10,c:'transition'},
  {n:29,s:'Cu',zh:'铜',en:'Copper',ipa:'/ˈkɒpər/',p:4,g:11,c:'transition'},
  {n:30,s:'Zn',zh:'锌',en:'Zinc',ipa:'/ˈzɪŋk/',p:4,g:12,c:'transition'},
  {n:31,s:'Ga',zh:'镓',en:'Gallium',ipa:'/ˈɡæliəm/',p:4,g:13,c:'post'},
  {n:32,s:'Ge',zh:'锗',en:'Germanium',ipa:'/dʒɜːrˈmeɪniəm/',p:4,g:14,c:'metalloid'},
  {n:33,s:'As',zh:'砷',en:'Arsenic',ipa:'/ˈɑːrsənɪk/',p:4,g:15,c:'metalloid'},
  {n:34,s:'Se',zh:'硒',en:'Selenium',ipa:'/səˈliːniəm/',p:4,g:16,c:'nonmetal'},
  {n:35,s:'Br',zh:'溴',en:'Bromine',ipa:'/ˈbroʊmiːn/',p:4,g:17,c:'halogen'},
  {n:36,s:'Kr',zh:'氪',en:'Krypton',ipa:'/ˈkrɪptɒn/',p:4,g:18,c:'noble'},
  {n:37,s:'Rb',zh:'铷',en:'Rubidium',ipa:'/ruːˈbɪdiəm/',p:5,g:1,c:'alkali'},
  {n:38,s:'Sr',zh:'锶',en:'Strontium',ipa:'/ˈstrɒntiəm/',p:5,g:2,c:'alkaline'},
  {n:39,s:'Y',zh:'钇',en:'Yttrium',ipa:'/ˈɪtriəm/',p:5,g:3,c:'transition'},
  {n:40,s:'Zr',zh:'锆',en:'Zirconium',ipa:'/zɜːrˈkoʊniəm/',p:5,g:4,c:'transition'},
  {n:41,s:'Nb',zh:'铌',en:'Niobium',ipa:'/naɪˈoʊbiəm/',p:5,g:5,c:'transition'},
  {n:42,s:'Mo',zh:'钼',en:'Molybdenum',ipa:'/məˈlɪbdənəm/',p:5,g:6,c:'transition'},
  {n:43,s:'Tc',zh:'锝',en:'Technetium',ipa:'/tɛkˈniːʃiəm/',p:5,g:7,c:'transition'},
  {n:44,s:'Ru',zh:'钌',en:'Ruthenium',ipa:'/ruːˈθiːniəm/',p:5,g:8,c:'transition'},
  {n:45,s:'Rh',zh:'铑',en:'Rhodium',ipa:'/ˈroʊdiəm/',p:5,g:9,c:'transition'},
  {n:46,s:'Pd',zh:'钯',en:'Palladium',ipa:'/pəˈleɪdiəm/',p:5,g:10,c:'transition'},
  {n:47,s:'Ag',zh:'银',en:'Silver',ipa:'/ˈsɪlvər/',p:5,g:11,c:'transition'},
  {n:48,s:'Cd',zh:'镉',en:'Cadmium',ipa:'/ˈkædmiəm/',p:5,g:12,c:'transition'},
  {n:49,s:'In',zh:'铟',en:'Indium',ipa:'/ˈɪndiəm/',p:5,g:13,c:'post'},
  {n:50,s:'Sn',zh:'锡',en:'Tin',ipa:'/ˈtɪn/',p:5,g:14,c:'post'},
  {n:51,s:'Sb',zh:'锑',en:'Antimony',ipa:'/ˈæntɪməni/',p:5,g:15,c:'metalloid'},
  {n:52,s:'Te',zh:'碲',en:'Tellurium',ipa:'/təˈljʊəriəm/',p:5,g:16,c:'metalloid'},
  {n:53,s:'I',zh:'碘',en:'Iodine',ipa:'/ˈaɪədiːn/',p:5,g:17,c:'halogen'},
  {n:54,s:'Xe',zh:'氙',en:'Xenon',ipa:'/ˈziːnɒn/',p:5,g:18,c:'noble'},
  {n:55,s:'Cs',zh:'铯',en:'Caesium',ipa:'/ˈsiːziəm/',p:6,g:1,c:'alkali'},
  {n:56,s:'Ba',zh:'钡',en:'Barium',ipa:'/ˈbɛəriəm/',p:6,g:2,c:'alkaline'},
  {n:57,s:'La',zh:'镧',en:'Lanthanum',ipa:'/ˈlænθənəm/',p:6,g:null,c:'lanthanide'},
  {n:58,s:'Ce',zh:'铈',en:'Cerium',ipa:'/ˈsɪəriəm/',p:6,g:null,c:'lanthanide'},
  {n:59,s:'Pr',zh:'镨',en:'Praseodymium',ipa:'/ˌpreɪziəˈdɪmiəm/',p:6,g:null,c:'lanthanide'},
  {n:60,s:'Nd',zh:'钕',en:'Neodymium',ipa:'/ˌniːəˈdɪmiəm/',p:6,g:null,c:'lanthanide'},
  {n:61,s:'Pm',zh:'钷',en:'Promethium',ipa:'/prəˈmiːθiəm/',p:6,g:null,c:'lanthanide'},
  {n:62,s:'Sm',zh:'钐',en:'Samarium',ipa:'/səˈmɛəriəm/',p:6,g:null,c:'lanthanide'},
  {n:63,s:'Eu',zh:'铕',en:'Europium',ipa:'/jʊəˈroʊpiəm/',p:6,g:null,c:'lanthanide'},
  {n:64,s:'Gd',zh:'钆',en:'Gadolinium',ipa:'/ˌɡædəˈlɪniəm/',p:6,g:null,c:'lanthanide'},
  {n:65,s:'Tb',zh:'铽',en:'Terbium',ipa:'/ˈtɜːrbiəm/',p:6,g:null,c:'lanthanide'},
  {n:66,s:'Dy',zh:'镝',en:'Dysprosium',ipa:'/dɪˈsproʊziəm/',p:6,g:null,c:'lanthanide'},
  {n:67,s:'Ho',zh:'钬',en:'Holmium',ipa:'/ˈhoʊlmiəm/',p:6,g:null,c:'lanthanide'},
  {n:68,s:'Er',zh:'铒',en:'Erbium',ipa:'/ˈɜːrbiəm/',p:6,g:null,c:'lanthanide'},
  {n:69,s:'Tm',zh:'铥',en:'Thulium',ipa:'/ˈθjuːliəm/',p:6,g:null,c:'lanthanide'},
  {n:70,s:'Yb',zh:'镱',en:'Ytterbium',ipa:'/ɪˈtɜːrbiəm/',p:6,g:null,c:'lanthanide'},
  {n:71,s:'Lu',zh:'镥',en:'Lutetium',ipa:'/ljuːˈtiːʃiəm/',p:6,g:null,c:'lanthanide'},
  {n:72,s:'Hf',zh:'铪',en:'Hafnium',ipa:'/ˈhæfniəm/',p:6,g:4,c:'transition'},
  {n:73,s:'Ta',zh:'钽',en:'Tantalum',ipa:'/ˈtæntələm/',p:6,g:5,c:'transition'},
  {n:74,s:'W',zh:'钨',en:'Tungsten',ipa:'/ˈtʌŋstən/',p:6,g:6,c:'transition'},
  {n:75,s:'Re',zh:'铼',en:'Rhenium',ipa:'/ˈriːniəm/',p:6,g:7,c:'transition'},
  {n:76,s:'Os',zh:'锇',en:'Osmium',ipa:'/ˈɒzmiəm/',p:6,g:8,c:'transition'},
  {n:77,s:'Ir',zh:'铱',en:'Iridium',ipa:'/ɪˈrɪdiəm/',p:6,g:9,c:'transition'},
  {n:78,s:'Pt',zh:'铂',en:'Platinum',ipa:'/ˈplætɪnəm/',p:6,g:10,c:'transition'},
  {n:79,s:'Au',zh:'金',en:'Gold',ipa:'/ˈɡoʊld/',p:6,g:11,c:'transition'},
  {n:80,s:'Hg',zh:'汞',en:'Mercury',ipa:'/ˈmɜːrkjəri/',p:6,g:12,c:'transition'},
  {n:81,s:'Tl',zh:'铊',en:'Thallium',ipa:'/ˈθæliəm/',p:6,g:13,c:'post'},
  {n:82,s:'Pb',zh:'铅',en:'Lead',ipa:'/ˈlɛd/',p:6,g:14,c:'post'},
  {n:83,s:'Bi',zh:'铋',en:'Bismuth',ipa:'/ˈbɪzməθ/',p:6,g:15,c:'post'},
  {n:84,s:'Po',zh:'钋',en:'Polonium',ipa:'/pəˈloʊniəm/',p:6,g:16,c:'post'},
  {n:85,s:'At',zh:'砹',en:'Astatine',ipa:'/ˈæstətiːn/',p:6,g:17,c:'halogen'},
  {n:86,s:'Rn',zh:'氡',en:'Radon',ipa:'/ˈreɪdɒn/',p:6,g:18,c:'noble'},
  {n:87,s:'Fr',zh:'钫',en:'Francium',ipa:'/ˈfrænsiəm/',p:7,g:1,c:'alkali'},
  {n:88,s:'Ra',zh:'镭',en:'Radium',ipa:'/ˈreɪdiəm/',p:7,g:2,c:'alkaline'},
  {n:89,s:'Ac',zh:'锕',en:'Actinium',ipa:'/ækˈtɪniəm/',p:7,g:null,c:'actinide'},
  {n:90,s:'Th',zh:'钍',en:'Thorium',ipa:'/ˈθɔːriəm/',p:7,g:null,c:'actinide'},
  {n:91,s:'Pa',zh:'镤',en:'Protactinium',ipa:'/ˌproʊtækˈtɪniəm/',p:7,g:null,c:'actinide'},
  {n:92,s:'U',zh:'铀',en:'Uranium',ipa:'/jʊəˈreɪniəm/',p:7,g:null,c:'actinide'},
  {n:93,s:'Np',zh:'镎',en:'Neptunium',ipa:'/nɛpˈtjuːniəm/',p:7,g:null,c:'actinide'},
  {n:94,s:'Pu',zh:'钚',en:'Plutonium',ipa:'/pluːˈtoʊniəm/',p:7,g:null,c:'actinide'},
  {n:95,s:'Am',zh:'镅',en:'Americium',ipa:'/ˌæməˈrɪsiəm/',p:7,g:null,c:'actinide'},
  {n:96,s:'Cm',zh:'锔',en:'Curium',ipa:'/ˈkjʊəriəm/',p:7,g:null,c:'actinide'},
  {n:97,s:'Bk',zh:'锫',en:'Berkelium',ipa:'/ˈbɜːrkliəm/',p:7,g:null,c:'actinide'},
  {n:98,s:'Cf',zh:'锎',en:'Californium',ipa:'/ˌkælɪˈfɔːrniəm/',p:7,g:null,c:'actinide'},
  {n:99,s:'Es',zh:'锿',en:'Einsteinium',ipa:'/aɪnˈstaɪniəm/',p:7,g:null,c:'actinide'},
  {n:100,s:'Fm',zh:'镄',en:'Fermium',ipa:'/ˈfɜːrmiəm/',p:7,g:null,c:'actinide'},
  {n:101,s:'Md',zh:'钔',en:'Mendelevium',ipa:'/ˌmɛndəˈliːviəm/',p:7,g:null,c:'actinide'},
  {n:102,s:'No',zh:'锘',en:'Nobelium',ipa:'/noʊˈbɛliəm/',p:7,g:null,c:'actinide'},
  {n:103,s:'Lr',zh:'铹',en:'Lawrencium',ipa:'/ləˈrɛnsiəm/',p:7,g:null,c:'actinide'},
  {n:104,s:'Rf',zh:'𬬻',en:'Rutherfordium',ipa:'/ˌrʌðərˈfɔːrdiəm/',p:7,g:4,c:'transition'},
  {n:105,s:'Db',zh:'𬭊',en:'Dubnium',ipa:'/ˈdjuːbniəm/',p:7,g:5,c:'transition'},
  {n:106,s:'Sg',zh:'𬭳',en:'Seaborgium',ipa:'/siːˈbɔːrɡiəm/',p:7,g:6,c:'transition'},
  {n:107,s:'Bh',zh:'𬭛',en:'Bohrium',ipa:'/ˈbɔːriəm/',p:7,g:7,c:'transition'},
  {n:108,s:'Hs',zh:'𬭶',en:'Hassium',ipa:'/ˈhæsiəm/',p:7,g:8,c:'transition'},
  {n:109,s:'Mt',zh:'鿏',en:'Meitnerium',ipa:'/maɪtˈnɪəriəm/',p:7,g:9,c:'transition'},
  {n:110,s:'Ds',zh:'𫟼',en:'Darmstadtium',ipa:'/dɑːrmˈstætiəm/',p:7,g:10,c:'transition'},
  {n:111,s:'Rg',zh:'𬬭',en:'Roentgenium',ipa:'/rɛntˈɡɛniəm/',p:7,g:11,c:'transition'},
  {n:112,s:'Cn',zh:'鿔',en:'Copernicium',ipa:'/ˌkoʊpərˈnɪsiəm/',p:7,g:12,c:'post'},
  {n:113,s:'Nh',zh:'鿭',en:'Nihonium',ipa:'/nɪˈhoʊniəm/',p:7,g:13,c:'post'},
  {n:114,s:'Fl',zh:'𫓧',en:'Flerovium',ipa:'/fləˈroʊviəm/',p:7,g:14,c:'post'},
  {n:115,s:'Mc',zh:'镆',en:'Moscovium',ipa:'/mɒˈskoʊviəm/',p:7,g:15,c:'post'},
  {n:116,s:'Lv',zh:'𫟷',en:'Livermorium',ipa:'/ˌlɪvərˈmɔːriəm/',p:7,g:16,c:'post'},
  {n:117,s:'Ts',zh:'鿬',en:'Tennessine',ipa:'/ˈtɛnɪsiːn/',p:7,g:17,c:'halogen'},
  {n:118,s:'Og',zh:'鿫',en:'Oganesson',ipa:'/ˌoʊɡəˈnɛsɒn/',p:7,g:18,c:'noble'}
];

window.CATEGORY_META = {
  alkali: {zh:'碱金属', en:'Alkali metal'},
  alkaline: {zh:'碱土金属', en:'Alkaline earth'},
  transition: {zh:'过渡金属', en:'Transition metal'},
  post: {zh:'后过渡金属', en:'Post-transition metal'},
  metalloid: {zh:'类金属', en:'Metalloid'},
  nonmetal: {zh:'非金属', en:'Nonmetal'},
  halogen: {zh:'卤素', en:'Halogen'},
  noble: {zh:'稀有气体', en:'Noble gas'},
  lanthanide: {zh:'镧系', en:'Lanthanide'},
  actinide: {zh:'锕系', en:'Actinide'}
};
